#!/usr/bin/env python3
"""
Global Installer for Devin Orchestrator

Installs devin-orchestrator to a global location (~/.devin-orchestrator/)
for use across all workspaces.
"""

import os
import shutil
import stat
import time
from pathlib import Path
import sys


def _on_rm_error(func, path, exc_info):
    """Make paths writable and retry removal (Windows-friendly)."""
    try:
        os.chmod(path, stat.S_IWRITE)
    except (OSError, NotImplementedError):
        pass
    func(path)


def _rmtree(path: Path):
    """Remove a directory tree, using the right callback signature for the Python version."""
    if sys.version_info >= (3, 12):
        shutil.rmtree(path, onexc=_on_rm_error)
    else:
        shutil.rmtree(path, onerror=_on_rm_error)


def _backup_path(path: Path) -> Path:
    """Create a timestamped backup of a file in its parent backups/ directory."""
    backups_dir = path.parent / "backups"
    backups_dir.mkdir(parents=True, exist_ok=True)
    suffix = str(int(time.time()))
    backup = backups_dir / f"{path.name}.{suffix}.bak"
    shutil.copy2(path, backup)
    return backup


def write_launcher(
    global_root: Path,
    python: str | None = None,
    dry_run: bool = False,
    bin_dir: Path | None = None,
):
    """Write the devin-orchestrator launcher."""
    if bin_dir is None:
        if sys.platform == "win32":
            # Windows: keep everything inside the global root so PATH doesn't matter
            bin_dir = global_root / "bin"
        else:
            # Linux/macOS: conventional user bin directory
            bin_dir = Path.home() / ".local" / "bin"

    python = python or sys.executable
    mcp_server = global_root / "mcp_server.py"
    mcp_server_str = str(mcp_server)

    if sys.platform == "win32":
        launcher = bin_dir / "devin-orchestrator.bat"
        content = f'@echo off\n"{python}" "{mcp_server_str}" %*\n'
    else:
        launcher = bin_dir / "devin-orchestrator"
        content = f"""#!/bin/sh
# devin-orchestrator MCP server launcher
# Generated by install.py -- do not edit by hand.
exec "{python}" "{mcp_server_str}" "$@"
"""

    if dry_run:
        print(f"Would write launcher: {launcher}")
        return

    bin_dir.mkdir(parents=True, exist_ok=True)
    if launcher.exists():
        _backup_path(launcher)
    launcher.write_text(content)
    if sys.platform != "win32":
        launcher.chmod(launcher.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"Installed launcher: {launcher}")


def install(
    global_root: Path | None = None,
    source_dir: Path | None = None,
    dry_run: bool = False,
    python: str | None = None,
):
    """
    Install devin-orchestrator to global location

    Args:
        global_root: Optional global root path (defaults to ~/.devin-orchestrator/)
        source_dir: Optional source directory (defaults to current directory)
        dry_run: If True, only print what would be done without actually doing it
    """
    # Determine paths
    if global_root is None:
        global_root = Path.home() / ".devin-orchestrator"

    if source_dir is None:
        source_dir = Path(__file__).parent

    python = python or sys.executable

    global_root = global_root.expanduser()
    source_dir = source_dir.expanduser()

    print("=== Installing Devin Orchestrator ===")
    if dry_run:
        print("DRY RUN MODE - No actual installation will be performed")
    print(f"Source: {source_dir}")
    print(f"Target: {global_root}")
    print()

    # Create global root
    if not dry_run:
        global_root.mkdir(parents=True, exist_ok=True)
    print(f"Would create global root: {global_root}")

    # Copy skills
    source_skills = source_dir / "devin_orchestrator" / "skills"
    target_skills = global_root / "skills"
    if source_skills.exists():
        if not dry_run:
            if target_skills.exists():
                _rmtree(target_skills)
            shutil.copytree(source_skills, target_skills)
        print(f"Would copy skills: {source_skills} -> {target_skills}")

    # Copy workflows
    source_workflows = source_dir / "devin_orchestrator" / "workflows"
    target_workflows = global_root / "workflows"
    if source_workflows.exists():
        if not dry_run:
            if target_workflows.exists():
                _rmtree(target_workflows)
            shutil.copytree(source_workflows, target_workflows)
        print(f"Would copy workflows: {source_workflows} -> {target_workflows}")

    # Copy workflow engine
    source_engine = source_dir / "devin_orchestrator"
    target_engine = global_root / "devin_orchestrator"
    if source_engine.exists():
        if not dry_run:
            if target_engine.exists():
                _rmtree(target_engine)
            shutil.copytree(source_engine, target_engine)
        print(f"Would copy workflow engine: {source_engine} -> {target_engine}")

    # Copy config
    source_config = source_dir / "devin_orchestrator" / "config.yaml"
    target_config = global_root / "config.yaml"
    if source_config.exists():
        if not dry_run:
            if target_config.exists():
                _backup_path(target_config)
            shutil.copy2(source_config, target_config)
        print(f"Would copy config: {source_config} -> {target_config}")

    # Copy dispatch and MCP entry-point scripts so any workspace can invoke them.
    # These live inside the devin_orchestrator package now.
    for script_name in ("dispatch_devin.py", "dispatch_skill.py", "mcp_server.py"):
        source_script = source_dir / "devin_orchestrator" / script_name
        target_script = global_root / script_name
        if source_script.exists():
            if not dry_run:
                shutil.copy2(source_script, target_script)
            print(f"Would copy entry script: {source_script} -> {target_script}")

    # Remove legacy bootstrap_path.py that is no longer needed
    legacy_bootstrap = global_root / "bootstrap_path.py"
    if not dry_run and legacy_bootstrap.exists():
        legacy_bootstrap.unlink()
        print(f"Removed legacy file: {legacy_bootstrap}")

    # Copy role files used by dispatch_devin.py
    source_roles = source_dir / "devin_orchestrator" / "roles"
    target_roles = global_root / "roles"
    if source_roles.exists():
        if not dry_run:
            if target_roles.exists():
                _rmtree(target_roles)
            shutil.copytree(source_roles, target_roles)
        print(f"Would copy roles: {source_roles} -> {target_roles}")

    # Create work and log directories
    work_dir = global_root / "work"
    if not dry_run:
        work_dir.mkdir(parents=True, exist_ok=True)
    print(f"Would create work directory: {work_dir}")

    logs_dir = global_root / "logs"
    if not dry_run:
        logs_dir.mkdir(parents=True, exist_ok=True)
    print(f"Would create logs directory: {logs_dir}")

    # Create a stable launcher
    write_launcher(global_root, python=python, dry_run=dry_run)

    if dry_run:
        print()
        print("=== Dry Run Complete ===")
        print("No changes were made.")
    else:
        print()
        print("=== Installation Complete ===")
        print(f"Global root: {global_root}")
        print(f"Skills: {target_skills}")
        print(f"Workflows: {target_workflows}")
        print(f"Workflow engine: {target_engine}")
        print(f"Config: {target_config}")
        print(f"Work directory: {work_dir}")
        print()
        print("To use devin-orchestrator from any workspace:")
        print("  - Skills are available at: " + str(target_skills))
        print("  - Workflows are available at: " + str(target_workflows))
        print("  - Workflow engine is available at: " + str(target_engine))
        print("  - Config is available at: " + str(target_config))
        print()
        print("For agent integration, prefer the devin-orchestrator MCP tools")
        print(
            "  (e.g. mcp0_dispatch_devin, mcp0_dispatch_skill, mcp0_implement, mcp0_run_workflow)."
        )
        print()
        print("To register this MCP server with all known agents, run:")
        exe = Path(python).name if python else ("python3" if sys.platform != "win32" else "py")
        print(f"  {exe} register_mcp.py")
        print()
        print(
            "Use the legacy scripts only as a fallback when MCP tools are not available:"
        )
        print(
            "  python "
            + str(global_root / "dispatch_skill.py")
            + " <skill> <session_id> <workspace> <is_reviewer> <focused_context>"
        )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Install devin-orchestrator to global location"
    )
    parser.add_argument(
        "global_root",
        nargs="?",
        help="Global root path (default: ~/.devin-orchestrator)",
    )
    parser.add_argument(
        "source_dir", nargs="?", help="Source directory (default: current directory)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Dry run - show what would be done without actually doing it",
    )
    parser.add_argument(
        "--python",
        default=None,
        help="Python executable to use in the launcher (default: this interpreter)",
    )

    args = parser.parse_args()

    global_root = Path(args.global_root) if args.global_root else None
    source_dir = Path(args.source_dir) if args.source_dir else None

    install(global_root, source_dir, dry_run=args.dry_run, python=args.python)
