#!/usr/bin/env python3
"""
Set up an external workspace to use the devin-orchestrator harness.

Run this script from the harness repo (or anywhere the global install is
visible) to scaffold a target workspace so that Cascade can be opened there
with full tool access while still dispatching through the global harness.

Created artifacts:
- <workspace>/.devin-orchestrator/config.yaml
- <workspace>/.devin-orchestrator/README.md
- <workspace>/.devin/workflows/ (optional, for local overrides)
- <workspace>/CASCADE-ORCHESTRATOR.md
"""

import argparse
from pathlib import Path


def setup_workspace(
    workspace: Path,
    global_root: Path | None = None,
    with_local_workflows: bool = False,
    dry_run: bool = False,
) -> None:
    workspace = workspace.expanduser().resolve()
    if global_root is None:
        global_root = Path.home() / ".devin-orchestrator"
    else:
        global_root = global_root.expanduser().resolve()

    if not workspace.exists():
        raise FileNotFoundError(f"Workspace does not exist: {workspace}")
    if not workspace.is_dir():
        raise NotADirectoryError(f"Workspace is not a directory: {workspace}")

    # Ensure the harness is installed globally.
    for required in (global_root / "skills", global_root / "workflows"):
        if not required.exists():
            raise FileNotFoundError(
                f"Global harness not found at {global_root}. "
                "Run 'python install.py' first."
            )

    orchestrator_dir = workspace / ".devin-orchestrator"
    workflows_dir = workspace / ".devin" / "workflows"

    if not dry_run:
        orchestrator_dir.mkdir(parents=True, exist_ok=True)
        if with_local_workflows:
            workflows_dir.mkdir(parents=True, exist_ok=True)

    # Workspace-local config: point at the global skills/workflows/engine and
    # set session_work_dir to this workspace so dispatch validation passes.
    config_path = orchestrator_dir / "config.yaml"
    config_template = f"""# Per-workspace devin-orchestrator configuration
# Generated by scripts/setup_workspace.py
# This config is merged over the global config when dispatch_devin.py or
# dispatch_skill.py are invoked with --work-dir pointing at this workspace.

# Global harness paths (share skills, workflows, and workflow engine)
global_root: {global_root.as_posix()}
skills_dir: {(global_root / "skills").as_posix()}
workflows_dir: {(global_root / "workflows").as_posix()}
workflow_engine_dir: {(global_root / "workflow-engine").as_posix()}

# Sessions for this workspace are isolated under the workspace itself.
session_work_dir: {workspace.as_posix()}

# Inherit or override Devin CLI settings from the global config. These are
# only needed if the workspace requires a different binary/model/permission.
devin_cli_path: ${"{DEVIN_CLI_PATH}"}
default_model: ${"{DEVIN_DEFAULT_MODEL:-swe-1.6}"}
default_permission_mode: ${"{DEVIN_DEFAULT_PERMISSION_MODE:-dangerous}"}
"""

    if not dry_run:
        config_path.write_text(config_template, encoding="utf-8")
    print(f"{'Would create' if dry_run else 'Created'} {config_path}")

    # README for the workspace-local orchestrator directory.
    readme_path = orchestrator_dir / "README.md"
    readme_content = f"""# devin-orchestrator workspace config

This workspace is configured to use the devin-orchestrator harness installed at:

    {global_root.as_posix()}

Cascade can dispatch Devin workers from this workspace using the global dispatch
scripts and `--work-dir {workspace.as_posix()}`.

See `CASCADE-ORCHESTRATOR.md` in the workspace root for the full integration
cheat sheet.
"""
    if not dry_run:
        readme_path.write_text(readme_content, encoding="utf-8")
    print(f"{'Would create' if dry_run else 'Created'} {readme_path}")

    # Cheat-sheet for Cascade opened in this workspace.
    cheat_sheet = workspace / "CASCADE-ORCHESTRATOR.md"
    cheat_content = f"""# Cascade Orchestrator Cheat Sheet

This workspace uses the `devin-orchestrator` harness from `{global_root.as_posix()}`.

## Quick dispatches

```powershell
# Direct Devin dispatch with a prompt file
py -3.14 {global_root.as_posix()}/dispatch_devin.py `
    --work-dir {workspace.as_posix()} `
    --role coder `
    --prompt-file prompt.md `
    --output-file result.md

# Dispatch a specific skill
py -3.14 {global_root.as_posix()}/dispatch_skill.py `
    brainstorming SESSION-001 {workspace.as_posix()}
```

## Core skills

- For end-to-end superpower: use `mcp0_run_workflow('superpower')` (preferred)
- `brainstorming`, `writing-plans` — planning
- `subagent-driven-development`, `test-driven-development`, `executing-plans` — implementation
- `code-review`, `requesting-code-review`, `receiving-code-review`, `adversarial-review` — review
- `systematic-debugging`, `swe-compliance`, `using-git-worktrees` — support
- `orchestrate-superpower` — legacy skill; now routes to `mcp0_run_workflow('superpower')` (deprecated)

## Core workflows

- `superpower` — full gated methodology (use with `mcp0_run_workflow`)
- `code_review`, `pr_review`, `rca`
- `devin-support` — deprecated wrapper; use `mcp0_run_workflow('superpower')` directly

## Local overrides

Optional per-workflow overrides can live in `.devin/workflows/`.
"""
    if not dry_run:
        cheat_sheet.write_text(cheat_content, encoding="utf-8")
    print(f"{'Would create' if dry_run else 'Created'} {cheat_sheet}")

    if with_local_workflows and not dry_run:
        print(f"Created local override directory: {workflows_dir}")
    elif with_local_workflows and dry_run:
        print(f"Would create local override directory: {workflows_dir}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Set up an external workspace to use devin-orchestrator"
    )
    parser.add_argument("workspace", help="Path to the workspace to set up")
    parser.add_argument(
        "--global-root",
        default=str(Path.home() / ".devin-orchestrator"),
        help="Path to the global devin-orchestrator install (default: ~/.devin-orchestrator)",
    )
    parser.add_argument(
        "--with-local-workflows",
        action="store_true",
        help="Create .devin/workflows/ for per-workflow overrides",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be created without writing files",
    )
    args = parser.parse_args()

    setup_workspace(
        Path(args.workspace),
        global_root=Path(args.global_root),
        with_local_workflows=args.with_local_workflows,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    main()
